
apiVersion: apps/v1
kind: Deployment
metadata:
  name: university-recommendation-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: university-recommendation
  template:
    metadata:
      labels:
        app: university-recommendation
    spec:
      containers:
      - name: university-recommendation
        image: <ECR_IMAGE_URL>
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: university-recommendation-service
spec:
  selector:
    app: university-recommendation
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
